services:
  user_service:
    build: 
      context: user_service
    command: ["--port", "8080"]
    environment:
      TASKS_MANAGER_ADDR: tasks_manager:8081
      STATISTICS_SERVICE_ADDR: statistics_service:8082
    ports:
      - 8080:8080
    depends_on:
      - user_db
      - tasks_manager
      - statistics_service
    restart: always

  user_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432


  tasks_manager:
    build: 
      context: tasks_manager
    command: ["--port", "8081"]
    ports:
      - 8081:8081
    depends_on:
      - task_db
    restart: always

  task_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_db
    volumes:
      - task_db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5433:5432


  statistics_service:
    build: 
      context: statistics_service
    command: ["--port", "8082"]
    ports:
      - 8082:8082
    depends_on:
      - kafka
      - statistics_db
    restart: always

  statistics_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statistics_db
    volumes:
      - statistics_db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5434:5432


  kafka:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_JMX_PORT: 9997
    ports:
      - "9092:9092"

  # kafka-ui:
  #   container_name: "kafka-ui"
  #   image: provectuslabs/kafka-ui
  #   restart: unless-stopped
  #   depends_on:
  #     - kafka
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: 'local'
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:29092'
  #     KAFKA_CLUSTERS_0_METRICS_PORT: 9997
  #     DYNAMIC_CONFIG_ENABLED: 'true'
  #   ports:
  #     - "8000:8080"

volumes:
  user_db_data:
  task_db_data:
  statistics_db_data:
