services:
  user_service:
    build: 
      context: user_service
    command: ["--port", "8080"]
    ports:
      - 8080:8080
    depends_on:
      - user_db
      - tasks_manager
    restart: always

  user_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432


  tasks_manager:
    build: 
      context: tasks_manager
    command: ["--port", "8081"]
    ports:
      - 8081:8081
    depends_on:
      - task_db
    restart: always

  task_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_db
    volumes:
      - task_db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5433:5432

volumes:
  user_db_data:
  task_db_data:
